# Generated by Django 4.1.3 on 2022-11-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="watched",
            field=models.BooleanField(default=False),
        ),
    ]
