# Generated by Django 4.1.3 on 2022-11-23 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_watched"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 23, 16, 37, 40, 326012),
                verbose_name="date published",
            ),
            preserve_default=False,
        ),
    ]
