# Generated by Django 4.1.3 on 2022-11-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="body",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
