# Generated by Django 4.1.3 on 2022-11-27 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movie_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 27, 19, 19, 32, 399598, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
    ]
