# Generated by Django 4.1.3 on 2022-11-28 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movie_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="currently_watching",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 28, 17, 41, 25, 953990, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
    ]
