# Generated by Django 4.1.3 on 2022-12-05 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_movie_currently_watching_alter_movie_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 5, 19, 11, 28, 851266, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
    ]
