# Generated by Django 4.1.3 on 2022-12-11 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_movie_trailer_alter_movie_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie", name="xmas", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 11, 14, 51, 12, 528578, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
    ]
